# Generated by Django 2.2.2 on 2019-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
