# Generated by Django 2.2.1 on 2019-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_text', models.TextField()),
                ('doc_date', models.DateTimeField(verbose_name='date input')),
            ],
        ),
    ]
