# Generated by Django 2.2.1 on 2019-05-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textvis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visdoc',
            name='doc_name',
            field=models.CharField(default='doc', max_length=64),
            preserve_default=False,
        ),
    ]
