# Generated by Django 2.2.1 on 2019-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textvis', '0003_auto_20190605_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdoc',
            name='avg_word_len',
            field=models.FloatField(default=0, verbose_name='Average Word Length'),
        ),
    ]
