# Generated by Django 2.2.2 on 2019-06-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_roll_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textvis', '0005_auto_20190606_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='visdoc',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visdoc',
            name='host_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
