# Generated by Django 2.2.2 on 2019-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textvis', '0006_auto_20190612_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='visdoc',
            name='retained',
            field=models.BooleanField(default=False),
        ),
    ]
