# Generated by Django 2.2.2 on 2019-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feud', '0002_auto_20190613_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
