# Generated by Django 2.2.2 on 2019-06-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feud', '0003_auto_20190615_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeudBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feud.Prompt')),
                ('voter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
