# Generated by Django 2.2.2 on 2019-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feud', '0005_auto_20190620_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='is_accepting_votes',
            field=models.IntegerField(choices=[(0, 'Waiting to Vote'), (1, 'Voting Open'), (2, 'Voting Complete')], default=0),
        ),
    ]
